### ISSUE TITLE
vue-chart.jsで軸の範囲の決め方

### ISSUE THREAD

**Issue by yama30120** [gotaku6629/Encourage#11]
ヒストグラムの縦軸を0から開始するようにしたかったが詰まったのでメモ。

optionsというのを設定すればうまくいきそうなのだがその方法がよくわからなかった。
以下のサイトを参考にし、ファイルを分けると成功した。
グラフは別のファイルに書いた方がよさそうな気がする。
https://qiita.com/kiyc/items/a94a202bf06fff644f62

**Comment by gotaku6629** [comment]
ご苦労様です。
